name: OnComment

on: [issue_comment]

env:
  EVENT_DATA: ${{ github.event }}

jobs:
  on-comment:

    runs-on: windows-latest
    
    steps:
    - name: On comment
      shell: cmd
      run: |
        echo %EVENT_DATA%
