name: OnComment

on: [issue_comment]

jobs:
  on-comment:

    runs-on: windows-latest
    
    env:
      EVENT_DATA: ${{ github.event }}

    steps:
    - name: On comment
      shell: cmd
      run: |
        echo %EVENT_DATA%
