name: OnComment

on: [issue_comment]

jobs:
  on-comment:

    runs-on: windows-latest
    
    steps:
    - name: On comment
      shell: cmd
      env:
        EVENT_DATA: ${{ toJson(github.event) }}
      run: |
        echo %EVENT_DATA%
